version: 2.1

jobs:
    build:

        docker:
            # Specify the version you desire here
            - image: cimg/php:8.3-node
            - image: cimg/mysql:8.0.33
              environment:
                  MYSQL_DATABASE: todo_test
                  MYSQL_ROOT_PASSWORD: root

        steps:
            - checkout

            - run: sudo apt update # PHP CircleCI 2.0 Configuration File# PHP CircleCI 2.0 Configuration File sudo apt install zlib1g-dev libsqlite3-dev

            - restore_cache:
                  keys:
                      - v1-dependencies-{{ checksum "composer.json" }}
                      - v1-dependencies-

            - run: composer clear-cache
            - run: composer install -n --prefer-dist -vvv

            - save_cache:
                  key: v1-dependencies-{{ checksum "composer.json" }}
                  paths:
                      - ./vendor
            - run: yes | php bin/console doctrine:schema:update -f --env=test || true
            - run: yes | php bin/console doctrine:fixtures:load --env=test || true
            - run: vendor/bin/phpstan
            - run: vendor/bin/phpunit
