version: 2.1

jobs:
    build:
        docker:
            - image: cimg/php:8.3-node
              environment:
                  MYSQL_DATABASE: test_db
                  MYSQL_ROOT_PASSWORD: root
            - image: cimg/mysql:8.0.33

        steps:
            - checkout
            - run: sudo apt update && sudo apt install -y libzip-dev unzip
            - run:
                  name: Install Composer Dependencies
                  command: composer install --prefer-dist --no-interaction
            - run:
                  name: Set Up Database
                  command: |
                      # Commandes pour configurer la base de données si nécessaire
                      php bin/console doctrine:database:create --env=test
                      php bin/console doctrine:migrations:migrate --env=test --no-interaction
            - run:
                  name: Run PHPUnit Tests
                  command: vendor/bin/phpunit --configuration phpunit.xml.dist
