version: 2.1

jobs:
    build:
        docker:
            - image: cimg/php:8.3-node
              environment:
                  MYSQL_DATABASE: test_db
                  MYSQL_ROOT_PASSWORD: root
            - image: cimg/mysql:8.0.33

        steps:
            - checkout
            - run: sudo apt update && sudo apt install -y libzip-dev unzip
            - restore_cache:
                    keys:
                        - v1-dependencies-{{ checksum "composer.json" }}
                        - v1-dependencies-

            - save_cache:
                    paths:
                        - ./vendor
                    key: v1-dependencies-{{ checksum "composer.json" }}
            - store_artifacts:
                    path: path/to/test-reports
                    destination: test-reports
            - run:
                  name: Install Composer Dependencies
                  command: composer install --prefer-dist --no-interaction
            - run:
                  name: Set Up Database
                  command: |
                      php bin/console doctrine:database:create --env=test
                      php bin/console doctrine:migrations:migrate --env=test --no-interaction
            - run:
                  name: Run PHPUnit Tests
                  command: vendor/bin/phpunit --configuration phpunit.xml.dist
